### ISSUE TITLE
Search 页面

### ISSUE THREAD

**Issue by benxie** [youcannotseethis/trunk#20]
1. 登录前能用此页面吗？
   2，需要search的：
   User(只能登陆后？）；
   Filter(需要吗？）
   Note(登录前只搜索public的，登陆后搜索所有的？时间条件？地点条件？还是只搜索关键字？）
   Place（关键字搜索，登录前即可）；

**Comment by jnozsc** [comment]
关于search 页面，搜 user 的页面可在登陆后才能做。

搜 note 的 search 页面，上面输入各种条件，下面列表即可。（这个页面完全不是为了一个产品做的，完全是为了展示 database 课程做的）我是这么理解的。

**Comment by jnozsc** [comment]
user 和 note 的 search 可以分开
